es:
  ips: http://localhost:9200/
biz:
  type: IM_CLOUD_DISK
  key: 0
logging:
  level:
    ROOT: info
  config: classpath:log4j2.xml
druid:
  driverClassName: com.mysql.fabric.jdbc.FabricMySQLDriver
  initialSize: 5
  minIdle: 5
  maxActive: 200
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: true
  testOnReturn: true
  poolPreparedStatements: 20
  maxPoolPreparedStatementPerConnectionSize:200
  filters: log4j
  url: jdbc:mysql:fabric://s1.rds.sdp.nd:32271/dev_mysql_file_service?fabricServerGroup=my_group_s2_3306&fabricUsername=admin&fabricPassword=ZB5dGGTJtsC8t7OQ&autoReconnect=true&useUnicode=true&characterEncoding=UTF8
  user: user_n6fHGK3966
  password: lp2sbe7DRe
  
cs:
 url:http://betacs.101.com/v0.1
 service_id:cc686f6e-7634-4357-ab4e-36dabfda6bbd
 service_name:preproduction_content_im_disk
